export const LabelIcons = [
    'pi pi-bookmark-fill',
    'pi pi-tag',
    'icon-error',
    'pi pi-tags',
    'pi pi-star',
    'pi pi-paperclip',
    'icon-language-1',
    'icon-archive',
    'pi pi-flag',
    'pi pi-eye',
    'icon-spellcheck',
    'icon-bug',
    'icon-language-2',
    'pi pi-clock',
    'pi pi-history',
    'pi pi-user-edit',
    'icon-lowercase',
    'icon-uppercase',
];
