export enum CommentSource {
    'Editor' = 1,
    'Translator' = 2,
    'Proofreader' = 3,
    'Reviewer' = 4,
    'Project Manager' = 5,
    'Translation Manager' = 6,
    'Supplier' = 7,
    'Project Create' = 10001,
    'Project Update' = 10002,
    'Mapping Assistant' = 10003,
    'Project Version' = 10004,
    'Project Recalculate' = 10005,
    'Translation Import' = 10006,
}
